version: '3'

services:
  database:
    container_name: nextcloud-db
    image: webhippie/mariadb:latest
    networks:
      - backend
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASS}
      MARIADB_DATABASE: ${NEXTCLOUD_DB_NAME}
      MARIADB_USERNAME: ${NEXTCLOUD_DB_USER}
      MARIADB_PASSWORD: ${NEXTCLOUD_DB_PASS}
    restart: always

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    networks:
      - backend
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/redis:/data
    restart: always

  solr:
    container_name: nextcloud-solr
    image: solr:6-alpine
    networks:
      - backend
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant
    restart: always

  collabora:
    container_name: nextcloud-collabora
    image: collabora/code:latest
    ports:
      - "9004:9980"
    networks:
      - frontends
      - backend
    environment:
      DOMAIN: ${COLLABORA_DOMAIN}
      VIRTUAL_HOST: ${COLLABORA_DOMAIN}
      LETSENCRYPT_HOST: ${COLLABORA_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    cap_add:
      - MKNOD
    tty: true
    restart: always

  nextcloud:
    container_name: nextcloud
    image: wonderfall/nextcloud:latest
    depends_on:
      - database
      - redis
      - solr
    networks:
      - frontends
      - backend
    ports:
      - "9003:8888"
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/data:/data
      - ${DOCKER_DATA_PATH}/nextcloud/config:/config
      - ${DOCKER_DATA_PATH}/nextcloud/apps:/apps2
      - ${DOCKER_DATA_PATH}/nextcloud/themes:/nextcloud/themes
    environment:
      UID: 1313
      GID: 1313
      UPLOAD_MAX_SIZE: 10G
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128
      CRON_PERIOD: 15m
      TZ: Europe/Berlin
      ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      DOMAIN: ${NEXTCLOUD_DOMAIN}
      DB_NAME: ${NEXTCLOUD_DB_NAME}
      DB_USER: ${NEXTCLOUD_DB_USER}
      DB_PASSWORD: ${NEXTCLOUD_DB_PASS}
      DB_TYPE: mysql
      DB_HOST: database
      VIRTUAL_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always

networks:
  frontends:
    external: true
  backend:
    internal: true
