version: '2'

networks:
  default:
    driver: bridge

services:
  nextcloud:
    image: wonderfall/nextcloud
    container_name: nextcloud
    depends_on:
      - nextcloud-db
      - solr
      - redis
      - collabora
    ports:
      - "8888:8888"
    environment:
      - UID=${NEXTCLOUD_UID}
      - GID=${NEXTCLOUD_GID}
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - DOMAIN=${NEXTCLOUD_DOMAIN}
      - DB_TYPE=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=nextcloud-db
      - VIRTUAL_HOST=${NEXTCLOUD_DOMAIN}
      - LETSENCRYPT_HOST=${NEXTCLOUD_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/data:/data
      - ${DOCKER_DATA_PATH}/nextcloud/config:/config
      - ${DOCKER_DATA_PATH}/nextcloud/apps:/apps2
      - ${DOCKER_DATA_PATH}/nextcloud/themes:/nextcloud/themes
    restart: always

  nextcloud-db:
    image: webhippie/mariadb
    container_name: nextcloud_mysql
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USERNAME=${MYSQL_USERNAME}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    restart: always

  solr:
    image: solr:6-alpine
    container_name: nextcloud_solr
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant
    restart: always

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    volumes:
      - ${DOCKER_DATA_PATH}/nextcloud/redis:/data
    restart: always

  collabora:
    image: collabora/code
    container_name: nextcloud_collabora
    ports:
      - "9980:9980"
    environment:
      - domain=${COLLABORA_DOMAIN}
      - VIRTUAL_HOST=${COLLABORA_DOMAIN}
      - LETSENCRYPT_HOST=${COLLABORA_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    cap_add:
      - MKNOD
    tty: true
    restart: always
