version: '3'

services:
  database:
    container_name: nextcloud-db
    image: webhippie/mariadb:latest
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASS}
      MARIADB_DATABASE: ${NEXTCLOUD_DB_NAME}
      MARIADB_USERNAME: ${NEXTCLOUD_DB_USER}
      MARIADB_PASSWORD: ${NEXTCLOUD_DB_PASS}
    restart: unless-stopped

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/redis:/data
    restart: always

  collabora:
    container_name: nextcloud-collabora
    image: collabora/code:latest
    networks:
      - frontends
    expose:
      - "9980"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/collabora:/etc/loolwsd
    environment:
      domain: ${COLLABORA_NEXTCLOUD_DOMAIN}
      username: ${COLLABORA_USER}
      password: ${COLLABORA_PASS}
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: ${COLLABORA_DOMAIN}
      LETSENCRYPT_HOST: ${COLLABORA_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    cap_add:
      - MKNOD
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: wanderfall/nextcloud:latest
    depends_on:
      - database
      - redis
    networks:
      - frontends
      - backend
    expose:
      - "8888"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/data:/data
      - ${DOCKER_DATA_PATH}/nextcloud/config:/config
      - ${DOCKER_DATA_PATH}/nextcloud/apps:/apps2
      - ${DOCKER_DATA_PATH}/nextcloud/themes:/nextcloud/themes
      - ${DOCKER_DATA_PATH}/nextcloud/session:/php/session
    environment:
      UID: 0
      GID: 0
      UPLOAD_MAX_SIZE: 10G
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128
      CRON_PERIOD: 15m
      TZ: Europe/Berlin
      ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      DOMAIN: ${NEXTCLOUD_DOMAIN}
      DB_NAME: ${NEXTCLOUD_DB_NAME}
      DB_USER: ${NEXTCLOUD_DB_USER}
      DB_PASSWORD: ${NEXTCLOUD_DB_PASS}
      DB_TYPE: mysql
      DB_HOST: database
      VIRTUAL_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped

networks:
  frontends:
    external: true
  backend:
    internal: true
