version: '3'

services:
  database:
    image: webhippie/mariadb:latest
    container_name: nextcloud-database
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASS}
      MARIADB_DATABASE: ${NEXTCLOUD_DB_NAME}
      MARIADB_USERNAME: ${NEXTCLOUD_DB_USER}
      MARIADB_PASSWORD: ${NEXTCLOUD_DB_PASS}
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASS}
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/redis:/data
    restart: unless-stopped

  # https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: nextcloud-onlyoffice
    networks:
    - backend
    expose:
    - '80'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKER_DATA_PATH}/nextcloud/onlyoffice/data:/var/www/onlyoffice/Data
    - ${DOCKER_DATA_PATH}/nextcloud/onlyoffice/log:/var/log/onlyoffice
    restart: unless-stopped

  # build from:
  # Apps wie hier z.B. beschrieben (mindestens OnlyOffice, FullTextSearch und Redis):
  # https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/blob/master/set_configuration.sh
  nextcloud:
    #image: benyanke/nextcloud:latest
    build: ./app
    container_name: nextcloud
    depends_on:
      - database
      - redis
      - onlyoffice
    networks:
      - frontends
      - backend
    expose:
      - "8888"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/data:/data
      - ${DOCKER_DATA_PATH}/nextcloud/config:/config
      - ${DOCKER_DATA_PATH}/nextcloud/apps:/apps2
      - ${DOCKER_DATA_PATH}/nextcloud/themes:/nextcloud/themes
      - ${DOCKER_DATA_PATH}/nextcloud/session:/php/session
    environment:
      UID: 1000
      GID: 1000
      UPLOAD_MAX_SIZE: 10G
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128
      CRON_PERIOD: 15m
      TZ: Europe/Berlin
      ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASS}
      DOMAIN: ${NEXTCLOUD_DOMAIN}
      DB_NAME: ${NEXTCLOUD_DB_NAME}
      DB_USER: ${NEXTCLOUD_DB_USER}
      DB_PASSWORD: ${NEXTCLOUD_DB_PASS}
      DB_TYPE: mysql
      DB_HOST: database
      APP_AUTO_UPDATE: 1
      VIRTUAL_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped

networks:
  frontends:
    external: true
  backend:
    internal: true
