version: '3'

services:
  database:
    image: webhippie/mariadb:latest
    container_name: nextcloud-database
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASS}
      MARIADB_DATABASE: ${NEXTCLOUD_DB_NAME}
      MARIADB_USERNAME: ${NEXTCLOUD_DB_USER}
      MARIADB_PASSWORD: ${NEXTCLOUD_DB_PASS}
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASS}
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/redis:/data
    restart: unless-stopped

  # https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: nextcloud-onlyoffice
    networks:
    - backend
    expose:
    - '80'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKER_DATA_PATH}/nextcloud/onlyoffice/data:/var/www/onlyoffice/Data
    - ${DOCKER_DATA_PATH}/nextcloud/onlyoffice/log:/var/log/onlyoffice
    restart: unless-stopped

  # https://github.com/instrumentisto/coturn-docker-image
  coturn:
    image: instrumentisto/coturn:latest
    container_name: nextcloud-turn
    networks:
    - frontends
    - backend
    expose:
    - '3478'
    - '3478/udp'
    - '49160-49200/udp'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKER_DATA_PATH}/nextcloud/turn/turnserver.conf:/etc/coturn/turnserver.conf
    - ${DOCKER_DATA_PATH}/nextcloud/turn/data:/var/lib/coturn
    environment:
      VIRTUAL_HOST: ${NEXTCLOUD_DOMAIN}
      VIRTUAL_PORT: 3478
      LETSENCRYPT_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  # https://github.com/nextcloud/fulltextsearch/wiki/Basic-Installation
  elasticsearch:
    build: ./elasticsearch
    container_name: nextcloud-elasticsearch
    networks:
    - backend
    expose:
    - "9200"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKER_DATA_PATH}/nextcloud/elasticsearch/readonlyrest.yml:/etc/elasticsearch/readonlyrest.yml
    - ${DOCKER_DATA_PATH}/nextcloud/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ${DOCKER_DATA_PATH}/nextcloud/elasticsearch/data:/usr/share/elasticsearch/data
    - ${DOCKER_DATA_PATH}/nextcloud/elasticsearch/log:/usr/share/elasticsearch/log
    environment:
    - cluster.name=nextcloud
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

  # https://github.com/tesseract-shadow/tesseract-ocr-re
  # https://github.com/daita/files_fulltextsearch_tesseract
#  tesseract:
#    image: tesseractshadow/tesseract4re:latest
#    container_name: nextcloud-tesseract
#    networks:
#    - backend
#    volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - ${DOCKER_DATA_PATH}/nextcloud/tesseract/tessdata:/usr/share/tessdata/
#    restart: always

  # https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/blob/master/set_configuration.sh
  nextcloud:
    build: ./app
    container_name: nextcloud
    depends_on:
      - database
      - redis
      - onlyoffice
      - coturn
      - elasticsearch
#      - tesseract
    networks:
      - frontends
      - backend
    expose:
      - "8888"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nextcloud/data:/data
      - ${DOCKER_DATA_PATH}/nextcloud/config:/config
      - ${DOCKER_DATA_PATH}/nextcloud/apps:/apps2
      - ${DOCKER_DATA_PATH}/nextcloud/themes:/nextcloud/themes
      - ${DOCKER_DATA_PATH}/nextcloud/session:/php/session
    environment:
      UID: 1000
      GID: 1000
      UPLOAD_MAX_SIZE: 10G
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128
      CRON_PERIOD: 15m
      TZ: Europe/Berlin
      ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASS}
      DOMAIN: ${NEXTCLOUD_DOMAIN}
      DB_NAME: ${NEXTCLOUD_DB_NAME}
      DB_USER: ${NEXTCLOUD_DB_USER}
      DB_PASSWORD: ${NEXTCLOUD_DB_PASS}
      DB_TYPE: mysql
      DB_HOST: database
      APP_AUTO_UPDATE: 1
      VIRTUAL_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_HOST: ${NEXTCLOUD_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped

networks:
  frontends:
    external: true
  backend:
    internal: true
