version: '3'

services:
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --cleanup
    restart: unless-stopped

networks:
  backend:
    internal: true
