version: '3'

services:
  dyndns:
    container_name: dyndns
    image: davd/docker-ddns:latest
    networks:
      - frontends
    ports:
      - "53:53"
      - "53:53/udp"
    expose:
      - "8080"
    volumes:
      - ${DOCKER_DATA_PATH}/dyndns:/var/cache/bind
    environment:
      SHARED_SECRET: ${DYNDNS_SECRET}
      ZONE: ${MY_DOMAIN}
      RECORD_TTL: 3600
      VIRTUAL_HOST: ${DYNDNS_DOMAIN}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${DYNDNS_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped

networks:
  frontends:
    external: true
