version: '3'

services:
  dyndns:
    container_name: dyndns
    image: davd/docker-ddns:latest
    networks:
      - frontends
    ports:
      - "9001:8080"
      - "53:53"
      - "53:53/udp"
    volumes:
      - ${DOCKER_DATA_PATH}/dyndns:/var/cache/bind
    environment:
      SHARED_SECRET: ${DYNDNS_SECRET}
      ZONE: ${MY_DOMAIN}
      RECORD_TTL: 3600
      VIRTUAL_HOST: ${DYNDNS_DOMAIN}
      LETSENCRYPT_HOST: ${DYNDNS_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always

networks:
  frontends:
    external: true
