version: '2'

networks:
  proxy-tier:
    external:
      name: proxy_network

services:
# alternatives:
# https://github.com/hoellen/dockerfiles/tree/master/boring-nginx
#
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy-tier
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/conf.d
      - ${DOCKER_DATA_PATH}/nginx/certs:/etc/nginx/certs:ro
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-docker-gen
    depends_on:
      - nginx
    environment:
      - DEFAULT_HOST=${MY_DOMAIN}
    volumes:
      - ${DOCKER_DATA_PATH}/nginx//nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    command: "-notify-sighup nginx-proxy -watch -wait 5s:30s -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx
      - docker-gen
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-docker-gen
    volumes:
      - ${DOCKER_DATA_PATH}/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    restart: always
