version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - frontends
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH}/nginx/certs:/etc/nginx/certs:ro
      - ${DOCKER_DATA_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_DATA_PATH}/nginx/html:/usr/share/nginx/html
      - ${DOCKER_DATA_PATH}/nginx/vhost.d:/etc/nginx/vhost.d
    restart: unless-stopped

  dockergen:
    container_name: dockergen
    image: jwilder/docker-gen:latest
    networks:
      - frontends
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${DOCKER_DATA_PATH}/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ${DOCKER_DATA_PATH}/nginx/certs:/etc/nginx/certs:ro
      - ${DOCKER_DATA_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_DATA_PATH}/nginx/html:/usr/share/nginx/html
      - ${DOCKER_DATA_PATH}/nginx/vhost.d:/etc/nginx/vhost.d
    environment:
      DEFAULT_HOST: ${MY_DOMAIN}
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    depends_on:
      - nginx
    networks:
      - frontends
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DATA_PATH}/nginx/certs:/etc/nginx/certs:rw
      - ${DOCKER_DATA_PATH}/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_DATA_PATH}/nginx/html:/usr/share/nginx/html
      - ${DOCKER_DATA_PATH}/nginx/vhost.d:/etc/nginx/vhost.d
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: dockergen
    restart: unless-stopped

networks:
  frontends:
    external: true
