version: '3'

services:
  database:
    container_name: wordpress-db
    image: webhippie/mariadb:latest
    networks:
      - backend
    volumes:
      - ${DOCKER_DATA_PATH}/wordpress/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASS}
      MARIADB_DATABASE: wordpress
      MARIADB_USERNAME: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASS}
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    depends_on:
      - database
    networks:
      - frontends
      - backend
    ports:
      - "9002:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      VIRTUAL_HOST: ${WORDPRESS_DOMAIN}
      LETSENCRYPT_HOST: ${WORDPRESS_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always

networks:
  frontends:
    external: true
  backend:
    internal: true
