version: '3'

services:
  database:
    container_name: hubzilla-db
    image: webhippie/mariadb:latest
    networks:
      - backend
    volumes:
      - ${DOCKER_DATA_PATH}/hubzilla/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${HUBZILLA_DB_ROOT_PASS}
      MARIADB_DATABASE: ${HUBZILLA_DB_NAME}
      MARIADB_USERNAME: ${HUBZILLA_DB_USER}
      MARIADB_PASSWORD: ${HUBZILLA_DB_PASS}
    restart: always

  hubzilla:
    container_name: hubzilla
    image: silviof/hubzilla-docker:latest
    depends_on:
      - database
    networks:
      - frontends
      - backend
    ports:
      - "9005:80"
    volumes:
      - ${DOCKER_DATA_PATH}/hubzilla/data:/data
    environment:
      SERVERNAME: ${HUBZILLA_DOMAIN}
      VIRTUAL_HOST: ${HUBZILLA_DOMAIN}
      LETSENCRYPT_HOST: ${HUBZILLA_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always

networks:
  frontends:
    external: true
  backend:
    internal: true
